name: Deploy to staging

on:
  push:
    branches:
      - debug-for-runtime-vars
jobs:
  deploy:
    uses: ./.github/workflows/_build_deploy.yml
    with:
      ckb-mode: testnet
      k8s-namespace: testnet
      k8s-workload: ckb-explorer-front
      environment: testnet
    secrets: inherit
